---
title: "scallops - trawl data set"
author: "Mike Allen"
date: "10/29/2021"
output: html_document
---

# load libraries and data
```{r}
library(tidyverse)
library(sf)
library(rnaturalearth)
library(here)
is.odd <- function(x) x %% 2 != 0

# read in trawl data, filter to just scallops (sent by Fred K)
dat <- readRDS("data_noaa/trawl/dat.rds") %>%
  filter(grepl(sppocean, pattern = "placopecten"))

# read in haul data (sent by Fred K)
# subset hauls to only include NEFSC_NEUS which has length
# other surveys with scallops:
# "DFO_ScotianShelf", "VIMS_NEAMAP", "DFO_Newfoundland" 
# "SCDNR_SEUS" is embedded within, but has no scallops
hauls_df_step1 <- readRDS("data_noaa/trawl/hauls.rds") %>%
  filter(region %in% c("NEFSC_NEUS")) %>%
  # fill all haul data with scallop wtcpue
  left_join(dat, by = "haulid") %>%
  select(-sppocean, -Freq, -presfit, -logwtcpue) %>%
  replace_na(list(wtcpue = 0)) %>%
  mutate(decade = case_when(year<1990 ~ "1980s", 
                            year>=1990 & year <2000 ~ "1990s",
                            year>=2000 ~ "2000s-2010s"),
         grid_lat = case_when(lat-trunc(lat)<0.5 ~ trunc(lat)+0.25,
                              lat-trunc(lat)>=0.5 ~ 
                                trunc(lat)+0.75),
         grid_lon = case_when(abs(lon-trunc(lon))<0.5 ~ 
                                trunc(lon)-0.25,
                              abs(lon-trunc(lon))>=0.5 ~ 
                                trunc(lon)-0.75),
         grid = paste0(grid_lat,grid_lon)) %>%
  arrange(haulid, year)

# Read in NEUS survey length data from OceanAdapt 
# originally obtained from Alexa F as "neus_Survdat.RData"
tlen <- readRDS("data_noaa/trawl/survdat.rds") %>%
  # filter to just scallops (401)
  filter(SVSPP == 401) %>%
  # divide into length bins (measures coarser than dredge survey)
  mutate(
    n_0_70 = ifelse(LENGTH <= 6, NUMLEN, 0),
    n_70_100 = ifelse(LENGTH > 6 & LENGTH < 10, NUMLEN, 0),
    n_100_up = ifelse(LENGTH >= 10, NUMLEN, 0),
    station_temp = case_when(nchar(STATION)==1 ~ 
                               paste0("00", as.character(STATION)),
                             nchar(STATION)==2 ~
                               paste0("0", as.character(STATION)),
                             nchar(STATION)==3 ~
                               as.character(STATION),
                             TRUE ~ "problem"),
    haulid = paste(CRUISE6,station_temp,STRATUM, sep = "-")) %>%
  select(-station_temp)

# include total catch number from tlen in hauls_df
hauls_df <- tlen %>%
  group_by(haulid) %>%
  summarize(n_catch_all = sum(NUMLEN, na.rm = T), # 23 NA, 1963: 17
            n_0_70 = sum(n_0_70),
            n_70_100 = sum(n_70_100), 
            n_100_up = sum(n_100_up), 
            .groups = "drop") %>%
  right_join(hauls_df_step1, by = "haulid") %>%
  replace_na(replace = list(n_catch_all = 0,
                            n_0_70 = 0,
                            n_70_100 = 0,
                            n_100_up = 0)) %>%
  arrange(haulid, year)
# note: haulid "201404-211-1100" has EXTREMELY high count (>150k)

# # make a data frame of all length-haulid combos for DRM age model
# tlen$length = as.numeric(floor(tlen$LENGTH))
# len = unique(tlen$length)[order(unique(tlen$length))][2:21]
# 
# hauls_drm_list <- list()
# for(i in len){
#   print(i)
# hauls_drm_list[[i]] <- hauls_df_step1 %>%
#   mutate(length = i,
#          spp = "Placopecten magellanicus") %>%
#   select(haulid, length, spp, btemp = bottemp, 
#          year, month, lat, lon) %>%
#   left_join(select(tlen,
#                    haulid,
#                    length,
#                    number_at_length = NUMLEN),
#                    by = c("haulid", "length")) %>%
#   select(haulid, length, spp, number_at_length,
#          btemp, year, month, lat, lon) %>%
#   replace_na(., list(number_at_length=0))
# }
# 
# hauls_drm <- do.call(rbind, hauls_drm_list)
# write.csv(hauls_drm, "output/scallop_catch_at_length_mo.csv",
#           row.names = F)
hauls_drm <- read.csv("output/scallop_catch_at_length_mo.csv")

# rm(hauls_df_step1)

# summarizing hauls data by 0.5 degree grid cell
hd_df = hauls_df %>%
    mutate(lat = grid_lat,
         lon = grid_lon) %>%
    group_by(grid, year, decade, lat, lon, 
           grid_lat, grid_lon) %>%
  summarize(mean_wtcpue = mean(wtcpue),
            mean_tot_num = mean(n_catch_all),
            mean_0_70 = mean(n_0_70),
            mean_70_100 = mean(n_70_100),
            mean_100_up = mean(n_100_up),
            n_hauls = length(wtcpue),
            mean_depth = mean(elev, na.rm = T),
            mean_bottemp = mean(bottemp, na.rm = T),
            .groups = "drop") %>%
  arrange(grid, year) %>%
  filter(lat >34)

# make data frames into sf objects and load spatial data
hauls <- hauls_df %>%
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326)

hd <- hd_df %>%
  st_as_sf(coords = c("grid_lon", "grid_lat"),
           crs = 4326)

state_bounds <- ne_coastline(scale = 10, returnclass = "sf") %>%
  st_crop(hd)

rm(hauls_df, dat)
```
# Plot 0.5 x 0.5 degree grid cell averages - mean catch by decade
```{r}
# summarize mean catch by decade
hd %>%
  group_by(grid, lat, lon, decade) %>%
  summarize(mean_catch = mean(mean_wtcpue),
            .groups = "drop") %>%
ggplot() +
  geom_tile(aes(x = lon, y = lat, fill = log10(mean_catch+1)), 
            alpha = 1, size = 0.25) +
  geom_sf(data = state_bounds, aes(), color = "gray",
          size = .25) +  theme_bw() +
  theme(text = element_text(size = 15),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 8)) +
  viridis::scale_fill_viridis(option = "inferno") +
  labs(x = "", y = "", fill = "log10(wt+1)") +
  facet_wrap(~decade)

# ggsave("figures/scallop_trawl_hd_mean_catch_by_decade.png",
#         height = 3, width = 7, dpi = 400)
```
# summarize mean depth by cell
```{r}
hd %>%
  group_by(grid, lat, lon) %>%
  summarize(mean_depth = mean(mean_depth),
            .groups = "drop") %>%
ggplot() +
  geom_tile(aes(x = lon, y = lat, fill = mean_depth), 
            alpha = 1, size = 0.25) +
  geom_sf(data = state_bounds, aes(), color = "gray",
          size = .25) +  theme_bw() +
  theme(text = element_text(size = 15),
        axis.text = element_text(size = 8)) +
  viridis::scale_fill_viridis(option = "inferno") +
  labs(x = "", y = "")

# ggsave("figures/scallop_trawl_hd_mean_depth.png",
#        height = 7, width = 7, dpi = 400)
```
# summarize mean bottom temperature by cell
```{r}
hd %>%
  group_by(grid, lat, lon) %>%
  summarize(mean_bottemp = mean(mean_bottemp, na.rm = T),
            .groups = "drop") %>%
ggplot() +
  geom_tile(aes(x = lon, y = lat, fill = mean_bottemp), 
            alpha = 1, size = 0.25) +
  geom_sf(data = state_bounds, aes(), color = "gray",
          size = .25) +  theme_bw() +
  theme(text = element_text(size = 15),
        axis.text = element_text(size = 8)) +
  viridis::scale_fill_viridis(option = "inferno") +
  labs(x = "", y = "")

# ggsave("figures/scallop_trawl_hd_mean_bottemp.png",
#        height = 7, width = 7, dpi = 400)

```
# plot time series for cells
```{r}
ts_plot_data <- hd %>%
  group_by(grid) %>%
  mutate(mean_hauls = mean(n_hauls),
         mean_bt = mean(mean_bottemp, na.rm = T),
         n_years = length(n_hauls),
         frac_zeros = sum(mean_wtcpue==0)/n_years) %>%
  filter(mean_hauls >= 1,
         n_years > 10,
         n_hauls > 0,
         frac_zeros < 0.75) %>%
  st_drop_geometry() %>%
  as.data.frame() %>%
  group_by(grid, lat, mean_bt, year, decade) %>%
  summarize(mean_wtcpue = mean(mean_wtcpue),
            mm_0_70 = mean(mean_0_70),
            mm_70_100 = mean(mean_70_100),
            mm_100_up = mean(mean_100_up),
            .groups = "drop") %>%
  pivot_longer(cols = mm_0_70:mm_100_up,
               names_to = "length",
               values_to = "num") %>%
  mutate(lat_band = fct_reorder(as.factor(trunc(lat)), 
                                as.numeric(trunc(lat)),
                                .desc = T),
         order = case_when(length == "mm_0_70" ~ 1,
                           length == "mm_70_100" ~ 2,
                           length == "mm_100_up" ~ 3),
         length = fct_reorder(length, order))

ts_plot_data  %>%
  ggplot() +
  geom_line(aes(x = as.numeric(year), y = log10(num+1), 
                color = mean_bt, group = grid)) +
  facet_grid(rows = vars(lat_band), cols = vars(length)) +
  viridis::scale_color_viridis() +
  labs(x = "") +
  theme_bw() +
  theme(text = element_text(size = 13)) +
  scale_x_continuous(breaks = c(1980, 2000, 2019),
                     labels = c(1980, 2000, 2019))

# ggsave("figures/scallop_trawl_hd_mean_catch_by_year.png",
#        height = 7, width = 10, dpi = 400)
```
# Plot 0.5 x 0.5 degree averages - mean catch by decade & size
```{r}
# summarize mean catch by decade and size
readRDS("data_noaa/trawl/survdat.rds") %>%
  # filter to just scallops (401)
  filter(SVSPP == 401) %>%
  # divide into length bins (measures coarser than dredge survey)
  mutate(
    n_0_40 = ifelse(LENGTH <= 4, NUMLEN, 0),
    n_40_80 = ifelse(LENGTH > 4 & LENGTH < 8, NUMLEN, 0),
    n_80_up = ifelse(LENGTH >= 8, NUMLEN, 0),
    station_temp = case_when(nchar(STATION)==1 ~ 
                               paste0("00", as.character(STATION)),
                             nchar(STATION)==2 ~
                               paste0("0", as.character(STATION)),
                             nchar(STATION)==3 ~
                               as.character(STATION),
                             TRUE ~ "problem"),
    haulid = paste(CRUISE6,station_temp,STRATUM, sep = "-")) %>%
  select(-station_temp) %>%
# include total catch number from tlen in hauls_df
  group_by(haulid) %>%
  summarize(n_catch_all = sum(NUMLEN, na.rm = T), # 23 NA, 1963: 17
            n_0_40 = sum(n_0_40),
            n_40_80 = sum(n_40_80), 
            n_80_up = sum(n_80_up), 
            .groups = "drop") %>%
  right_join(hauls_df_step1, by = "haulid") %>%
  replace_na(replace = list(n_catch_all = 0,
                            n_0_40 = 0,
                            n_40_80 = 0,
                            n_80_up = 0)) %>%
  arrange(haulid, year) %>%
#note: haulid "201404-211-1100" has EXTREMELY high count (>150k)
# summarizing hauls data by 0.5 degree grid cell
    mutate(lat = grid_lat,
         lon = grid_lon) %>%
    group_by(grid, year, decade, lat, lon, 
           grid_lat, grid_lon) %>%
  summarize(mean_wtcpue = mean(wtcpue),
            mean_tot_num = mean(n_catch_all),
            mean_0_40 = mean(n_0_40),
            mean_40_80 = mean(n_40_80),
            mean_80_up = mean(n_80_up),
            n_hauls = length(wtcpue),
            mean_depth = mean(elev, na.rm = T),
            mean_bottemp = mean(bottemp, na.rm = T),
            .groups = "drop") %>%
  arrange(grid, year) %>%
  filter(lat >34) %>%
# make data frames into sf objects and load spatial data
  st_as_sf(coords = c("grid_lon", "grid_lat"),
           crs = 4326) %>%
  group_by(grid) %>%
  mutate(mean_hauls = mean(n_hauls),
         mean_bt = mean(mean_bottemp, na.rm = T),
         n_years = length(n_hauls),
         frac_zeros = sum(mean_wtcpue==0)/n_years) %>%
  st_drop_geometry() %>%
  as.data.frame() %>%
  group_by(grid, lat, lon, mean_bt, year, decade) %>%
  summarize(mean_wtcpue = mean(mean_wtcpue),
            mm_0_40 = mean(mean_0_40),
            mm_40_80 = mean(mean_40_80),
            mm_80_up = mean(mean_80_up),
            .groups = "drop") %>%
  rename("Size 0-40 mm" = mm_0_40,
         "Size 40-80 mm" = mm_40_80,
         "Size >80 mm" = mm_80_up) %>%
  pivot_longer(cols = starts_with("Size"),
               names_to = "length",
               values_to = "num") %>%
  mutate(order = case_when(length == "Size 0-40 mm" ~ 1,
                           length == "Size 40-80 mm" ~ 2,
                           length == "size >80 mm" ~ 3)) %>%
  mutate(length = forcats::fct_reorder(length, order)) %>%
ggplot() +
  geom_tile(aes(x = lon, y = lat, fill = log10(num+1)), 
            alpha = 1, size = 0.25) +
  geom_sf(data = state_bounds, aes(), color = "gray",
          size = .25) +  theme_bw() +
  theme(text = element_text(size = 15),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 8)) +
  viridis::scale_fill_viridis(option = "inferno") +
  labs(x = "", y = "", fill = "log10(num+1)") +
  facet_grid(rows = vars(decade), cols = vars(length))

# ggsave("figures/scallop_trawl_hd_mean_catch_by_decade_length.png",
#         height = 7, width = 7, dpi = 400)
```