# See scallop_model_runs google sheet for more info about cell groups

# MA_9
MA_9 <- data.frame(
  grid_lon = c(-73.25, -72.75, -72.25,
               -73.25, -72.75, -72.25,
               -73.25, -72.75, -72.25),
  grid_lat = c(40.25, 40.25, 40.25,
               39.75, 39.75, 39.75,
               39.25, 39.25, 39.25)
) %>%
  mutate(grid = paste0(grid_lat, grid_lon))

#imputing for MA_9
dat_train_dens[165,"mean_dens"] <- 2.65
dat_train_dens[211,"mean_dens"] <- 3.67

# MA_14
MA_14 <- data.frame(
  grid_lon = c(-73.25, -72.75, -72.25,
               -73.25, -72.75, -72.25,
               -73.25, -72.75, -72.25,
               -72.75, -73.25, -73.75,
               -73.25, -73.75, -74.25),
  grid_lat = c(40.25, 40.25, 40.25,
               39.75, 39.75, 39.75,
               39.25, 39.25, 39.25,
               38.75, 38.75, 38.75,
               38.25, 38.25, 38.25)
) %>%
  mutate(grid = paste0(grid_lat, grid_lon)) %>%
  filter(grid != "38.25-73.25") # has only 14 yrs data 1980-2014

#imputing for MA_14
dat_train_dens[c(69,82,86,159,163,175),"mean_dens"] <- 0
dat_train_dens[315,"mean_dens"] <- 2.65
dat_train_dens[361,"mean_dens"] <- 3.67

# A_112
# 112 cells that result from max_NA = 4, years = 1980:2014

# A_40
# 40 cells that result from max_NA = 0, years = 1968:2014

# A_9
# top 9 cells from the subset generated by train_years = 1980:2014 and max_NA = 0
# and topn = 9

# A_16
# same as A_9 but with topn = 16


